### ISSUE TITLE
Multi-lingual Keyboard Layouts

### ISSUE THREAD

**Issue by HughP** [michaeldickens/Typing#16]
So, I am looking at multi-lingual and monolingual (moronity language) keyboard layouts. I have several corpora I would like to run, and evaluate several languages to get suggested layouts. Three things I don't quickly see when I read over the documentation here is:
1. the use of dead keys or special modifier keys (I have a lot of these in my current set up to mark diacritics, but dead keys can also be used and point in different directions - like to print to the screen of a solo instance of a unicode diacritic mark - without the base character), and how to make the application aware of those methods for input (or even suggest them).
2.  how does one tell the program if the keyboard is a ANSI keyboard or an ISO keyboard? see link for difference: http://deskthority.net/wiki/ANSI_vs_ISO
3. Where do I put the corpus of keystrokes to be analyzed? am I supposed to be looking for a file to past the text into? I diagramed my understanding of the application - though I understand that trigraphs are not currently implemented.

![untitled 2](https://cloud.githubusercontent.com/assets/40230/3463982/01d6c40a-0244-11e4-8ca7-a3cc7deddb07.jpg)

**Comment by HughP** [comment]
@michaeldickens you suggested that you might still have a bigram script?
> I generate characters and digraphs using a separate program. I don't have the program right now but I'll try and add it in some time this week.

Were you able to upload that?

**Comment by michaeldickens** [comment]
@HughP Sorry about the delay! I realized that modifying the character/digraph counter to where I can release it will require a bit of work. I'll put something on my calendar and try to finish it later this week, since I've got some free time.

**Comment by michaeldickens** [comment]
@HughP I uploaded my frequency counter here: https://github.com/michaeldickens/frequency 

It shouldn't be too hard to modify to do what you want. The function `freq_read_files` in `frequency.c` does most of the work.

**Comment by HughP** [comment]
Thank you.
