### ISSUE TITLE
Understanding the scores

### ISSUE THREAD

**Issue by iandoug** [michaeldickens/Typing#20]
hi Michael

Have started playing with your program, and also comparing its results to what http://spwebgames.com/keyboard/ says. Naturally the results don't agree, as far as I can interpret them.

To that end, 2 questions ... one of your commentators on your blog had single-scores for the layouts, any idea where those came from?

Also, please advise if below is correct. At this point I'm assuming that "Fitness" is the overall score.

Fitness:       higher is better
Distance:      lower is better
Finger work:  lower is better (how to interpret 0?)
Inward rolls:  higher is better
Outward rolls: lower is better
Same hand:     lower is better
Same finger:   lower is better
Row change:    lower is better
Home jump:     lower is better
Ring jump:     lower is better
To center:     lower is better

Also is there a way to tell "algorithm" to start with a specific layout?

Thanks, Ian

**Comment by michaeldickens** [comment]
Lower fitness is better. All the other factors add to fitness, so positive numbers increase fitness (make it worse) and negative numbers decrease it. The final score is called `fitness` as an artifact of the fact that I used to use genetic algorithms, but maybe it should be called `cost` instead. Fitness effectively tells you how much it costs to type the entire corpus using a given keyboard layout.

The starting layout is set by `keyboard.c:initKeyboard()`. The keyboard is set to equal `tools.h:DEFAULT_KEYBOARD_30` (or `_STANDARD` or `_KINESIS` depending on what mode you're in). But then it gets shuffled, so if you don't want to do that, you should remove the call to `shuffleKeyboard()` in keyboard.c line 117, near the beginning of `initKeyboard()`.
